### ISSUE TITLE
Failed to deploy cluster

### ISSUE THREAD

**Issue by hkpanchani** [Rbillon59/jmeter-k8s-starterkit#7] opened 2021-12-06 06:05 UTC
k8s/tool/telegraf/telegraf-operator.yaml deployment fails
Kubernetes Version: `v1.22.2`

`error: error validating "k8s/tool/telegraf/telegraf-operator.yaml": error validating data: [ValidationError(MutatingWebhookConfiguration.webhooks[0]): missing required field "sideEffects" in io.k8s.api.admissionregistration.v1.MutatingWebhook, ValidationError(MutatingWebhookConfiguration.webhooks[0]): missing required field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1.MutatingWebhook]; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by hkpanchani** [comment] 2021-12-06 06:28
change the file as below
![image](https://user-images.githubusercontent.com/35301566/144798059-da5b83d7-296f-4cf5-b3f1-cad157d0aabf.png)

Error gone cluster deployed, but now unable to start the telegraf container with following error.

`Error: failed to start container "telegraf": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/var/run/utmp" to rootfs at "/var/run/utmp" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**Comment by Rbillon59** [comment] 2021-12-06 15:08
Hi @hkpanchani 

I'am making a PR to update the rbac and the telegraf operator to avoid the v1beta deprecation. 

I'am taking note of the change you provided, and locally, on an older version (1.15) this seems backward compatible. Thanks you for providing the solution.

For your second issue, it seems something recurrent (was already a [problem](https://github.com/influxdata/telegraf/issues/5398) back in 2019) because, the location / presence of this file change on the different linux distros. I'am reproducting your issue locally on docker-desktop on windows with debian sub-system for example.

Because the informations given by utmp are not that critical (system uptime, login, logout, some events). I have commented it by default. As there is no really fully generic way to make it work everytime and not everybody is fine with debugging this kind of thing, I would consider the simpler, the better.

**Comment by Rbillon59** [comment] 2021-12-06 15:50
@hkpanchani Coud you please checkout the #8 PR and try again with the change. Let me know if all work as expected and I would merge.

Have a nice day, thanks you again for your feedback

**Comment by Rbillon59** [comment] 2021-12-11 15:19
I had time to test it by myself and everything seems to work, even with the latest version on my minikube (1.22.3).
I merged the PR in the master branch. Let me know if things goes wrong on your side.

I'am closing the issue in the meantime

**Closed by Rbillon59** 2021-12-11 15:19 UTC
